#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "lasuite-meet"
name = "La Suite - Meet"
description.en = "Simple and Secure Video Conferencing"
description.fr = "Solution simple et sécurisée de visioconférence"

version = "1.31.0~ynh1"

maintainers = ["fflorent", "rouja"]

[upstream]
license = "MIT"
website = "https://visio.numerique.gouv.fr/"
demo = "https://visio.numerique.gouv.fr/"
code = "https://github.com/suitenumerique/meet"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false

ldap = false
sso = true

disk = "1.5G"
ram.build = "1G"
ram.runtime = "200M"

[install]

    # TODO: Once removed, also remove the Prerequisites section of the description
    [install.dex]
    type = "app"
    filter = "match(id, '^(dex)(__[0-9+])?$')"
    ask.en = "Select the Dex app that will handle authentication."
    ask.fr = "Sélectionnez l'app Dex qui gérera l'authentification."
    help.en = "You need to have at least one instance of Dex installed beforehand on your server."
    help.fr = "Vous devez avoir au moins une instance de Dex préalablement installée sur votre serveur."

    [install.domain]
    type = "domain"

    [install.turn_domain]
    type = "domain"
    ask.en = "Select another domain for the Turn server (it will be created for you)"
    ask.fr = "Sélectionnez un autre domaine pour le serveur Turn (qui sera créé pour vous)"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr-fr", "en-us"]
    default = "fr-fr"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/suitenumerique/meet/archive/refs/tags/v1.31.0.tar.gz"
    sha256 = "e7c1793b351c9c89ce89be8e800a2dceb728ea97e4027486173940581b576b82"
    autoupdate.strategy = "latest_github_tag"

    [resources.sources.livekit]
    amd64.url = "https://github.com/livekit/livekit/releases/download/v1.13.6/livekit_1.13.6_linux_amd64.tar.gz"
    amd64.sha256 = "2b61abef2b9ba14b4b8ca38b37de9a37ffc682b9931d5fc03ceca2f0b77d3e33"
    arm64.url = "https://github.com/livekit/livekit/releases/download/v1.13.6/livekit_1.13.6_linux_arm64.tar.gz"
    arm64.sha256 = "5c75f09173199f3f8fe0c3c0d5a41171f9b306ffce6843d752c276d11e77d19b"
    armhf.url = "https://github.com/livekit/livekit/releases/download/v1.13.6/livekit_1.13.6_linux_armv7.tar.gz"
    armhf.sha256 = "adfbfa8159b1291b99d49a34c4486379de6c0ea91ea2f73d1bbfd7e460a9c604"
    in_subdir=false
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/livekit/livekit"
    autoupdate.asset.amd64 = ".*amd64.tar.gz"
    autoupdate.asset.arm64 = ".*arm64.tar.gz"
    autoupdate.asset.armhf = ".*armv7.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    turn.url = "__TURN_DOMAIN__/"
    turn.show_tile = false
    turn.allowed = "visitors"

    livekit.url = "/livekit"
    livekit.show_tile = false
    livekit.allowed = "visitors"
    livekit.auth_header = false
    livekit.protected = true

    [resources.ports]
    backend.default = 8071
    # Ports for livekit
    # Documentation here: https://docs.livekit.io/home/self-hosting/ports-firewall/
    livekit.default = 7880 # Handled by nginx with SSL termination, on port 443
    tcp.default = 7881
    tcp.exposed = "TCP"

    turn.default = 5349

    turn_udp.default = 3478
    turn_udp.exposed = "UDP"

    [resources.apt]
    packages = "redis, python3, python3-venv, python3-setuptools, python3-pip, postgresql, rdfind"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "22"
