#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "visio"
name = "Visio"
description.en = "Simple, high-performance videoconferencing solution powered by Livekit"
description.fr = "Solution simple et performante de visioconférence propulsé par Livekit"

version = "0.1.18~ynh1"

maintainers = ["fflorent", "rouja"]

[upstream]
license = "MIT"
website = "https://visio.numerique.gouv.fr/"
demo = "https://visio.numerique.gouv.fr/"
code = "https://github.com/suitenumerique/meet"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armv7"]
multi_instance = true

ldap = "false"

sso = "true"

# FIXME: replace with an **estimate** minimum disk and RAM requirements. e.g. 20M, 400M, 1G...
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr-fr", "en-us"]
    default = "fr-fr"

    [install.dex_domain]
    ask.en = "Domain for authentication. It can't be the same domain as above. Dex app will be installed and used for the authentication mechanism."
    ask.fr = "Domaine pour l'authentification. Il ne peut pas s'agir du même domaine que ci-dessus. L'application Dex sera installée et utilisée pour le mécanisme d'authentification."
    type = "domain"

    [install.dex_path]
    ask.en = "Path for authentication URL. Please don't use 'auth' as it will break NGINX configuration."
    ask.fr = "Chemin de l'URL d'authentification. Veuillez ne pas utiliser 'auth' car cela casserait la configuration NGINX."
    type = "path"
    default = "/"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/suitenumerique/meet/archive/refs/tags/v0.1.18.tar.gz"
    sha256 = "5fe1b0773556f221623ad5933f5ce42fc117715fe0b7ad630db1f9e72badc601"
    autoupdate.strategy = "latest_github_tag"

    [resources.sources.livekit]
    amd64.url = "https://github.com/livekit/livekit/releases/download/v1.8.0/livekit_1.8.0_linux_amd64.tar.gz"
    amd64.sha256 = "7ccd6c865a8c81909a1be63639ae0e6e80dff5e0d12cd1fffff3dadb53167cca"
    arm64.url = "https://github.com/livekit/livekit/releases/download/v1.8.0/livekit_1.8.0_linux_arm64.tar.gz"
    arm64.sha256 = "b9246a7e876a37f659f17c151acc82f665d5e173c1fa4ac937f222d944b2db0b"
    armv7.url = "https://github.com/livekit/livekit/releases/download/v1.8.0/livekit_1.8.0_linux_armv7.tar.gz"
    armv7.sha256 = "76e677080fe176b7a07d1280b08e72b942d65c303d36aa89979da6293631b039"
    in_subdir=false
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    backend.default = 8071
    # Ports for livekit
    # Documentation here: https://docs.livekit.io/home/self-hosting/ports-firewall/
    livekit.default = 7880 # Handled by nginx with SSL termination, on port 443
    tcp.default = 7881
    tcp.exposed = "TCP"

    [resources.apt]
    packages = "redis, python3, python3-setuptools, python3-pip, postgresql, rdfind, celery"

    [resources.database]
    type = "postgresql"
