#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "meet"
name = "Meet"
description.en = "Simple and Secure Video Conferencing. Powered by LiveKit."
description.fr = "Solution simple et sécurisée de visioconférence. Propulsée par Livekit."

version = "0.1.21~ynh2"

maintainers = ["fflorent", "rouja"]

[upstream]
license = "MIT"
website = "https://visio.numerique.gouv.fr/"
demo = "https://visio.numerique.gouv.fr/"
code = "https://github.com/suitenumerique/meet"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false

ldap = false

sso = true

disk = "1.5G"
ram.build = "1G"
ram.runtime = "200M"

[install]
    [install.dex]
    type = "app"
    filter = "match(id, '^(dex)(__[0-9+])?$')"
    ask.en = "Select the Dex app that will handle authentication."
    ask.fr = "Sélectionnez l'app Dex qui gérera l'authentification."
    help.en = "You need to have at least one instance of Dex installed beforehand on your server."
    help.fr = "Vous devez avoir au moins une instance de Dex préalablement installée sur votre serveur."

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr-fr", "en-us"]
    default = "fr-fr"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/suitenumerique/meet/archive/refs/tags/v0.1.21.tar.gz"
    sha256 = "5aa384d740023695bedb36b9602e8590f1ac4527c73826845b0e4a2ce1563d7b"
    autoupdate.strategy = "latest_github_tag"

    [resources.sources.livekit]
    amd64.url = "https://github.com/livekit/livekit/releases/download/v1.8.0/livekit_1.8.0_linux_amd64.tar.gz"
    amd64.sha256 = "7ccd6c865a8c81909a1be63639ae0e6e80dff5e0d12cd1fffff3dadb53167cca"
    arm64.url = "https://github.com/livekit/livekit/releases/download/v1.8.0/livekit_1.8.0_linux_arm64.tar.gz"
    arm64.sha256 = "b9246a7e876a37f659f17c151acc82f665d5e173c1fa4ac937f222d944b2db0b"
    armhf.url = "https://github.com/livekit/livekit/releases/download/v1.8.0/livekit_1.8.0_linux_armv7.tar.gz"
    armhf.sha256 = "76e677080fe176b7a07d1280b08e72b942d65c303d36aa89979da6293631b039"
    in_subdir=false
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    backend.default = 8071
    # Ports for livekit
    # Documentation here: https://docs.livekit.io/home/self-hosting/ports-firewall/
    livekit.default = 7880 # Handled by nginx with SSL termination, on port 443
    tcp.default = 7881
    tcp.exposed = "TCP"

    [resources.apt]
    packages = "redis, python3, python3-venv, python3-setuptools, python3-pip, postgresql, rdfind, celery"

    [resources.database]
    type = "postgresql"
