#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]


    preinstall = """
    sudo yunohost tools update apps
    sudo yunohost domain add dex.domain.tld
    sudo yunohost app install dex -f -a "domain=dex.domain.tld&path=/&oidc_name=&oidc_secret=&oidc_callback"
    """

    preupgrade = """
    sudo yunohost app remove dex__2 || true
    sudo yunohost app upgrade dex -u dex -F
    """

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.dex = "dex"

    test_upgrade_from.57d24f0.name = "Upgrade from 0.1.23~ynh1"
