#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]


    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.dex_domain = "domain.tld"
    args.dex_path = "/dex"

    test_upgrade_from.cdfc908.name = "Upgrade from 0.1.19~ynh1"
