#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

redis_db=$(ynh_app_setting_get --key=redis_db)
celery_redis_db=$(ynh_app_setting_get --key=celery_redis_db)
dex_app=$(ynh_app_setting_get --key=dex_app)

ynh_redis_remove_db "$redis_db"
ynh_redis_remove_db "$celery_redis_db"

ynh_config_remove_logrotate

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
ynh_config_remove_systemd

if ynh_hide_warnings yunohost service status "${app-livekit}" >/dev/null; then
    yunohost service remove "${app}-livekit"
fi
ynh_config_remove_systemd "${app}-livekit"

ynh_config_remove_nginx

ynh_script_progression "Removing $dex_app"
yunohost app remove "$dex_app"

ynh_script_progression "Close RTC port range"

if yunohost firewall list | grep -q "\- 49152:65535"; then
	ynh_hide_warnings yunohost firewall disallow UDP 49152:65535
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
